version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Allen.AliyunDDNSClient.sln && dotnet publish ./Allen.AliyunDDNSClient.sln -c Release -o ./obj/Docker/publish"
